fmod Bits is 

sort Bits Bit .
ops 0 1 : -> Bit [ctor] .
op nil : -> Bits [ctor] .
op _ _ : Bits Bit -> Bits [ctor] .
op neg : Bits -> Bits .
op _+_ : Bits Bits -> Bits .
vars b b' : Bit .
vars B B' : Bits . 

eq neg(nil) = nil .
eq neg(B 0) = neg(B) 1 .
eq neg(B 1) = neg(B) 0 .

eq nil + B = B .
eq B + nil = B .
eq (B 0) + (B' 0) = (B + B') 0 .
eq (B 1) + (B' 0) = (B + B') 1 .
eq (B 0) + (B' 1) = (B + B') 1 .
eq (B 1) + (B' 1) = ((nil 1) + (B + B')) 0 .

endfm
